# Generated by Django 3.0.2 on 2020-03-02 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('measurement', '0002_auto_20200303_0048'),
        ('calc_pnn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PnnData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnn_time', models.FloatField(verbose_name='pnn_time')),
                ('pnn', models.FloatField(verbose_name='pnn')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Measurement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='HeartBeat',
        ),
    ]
