# Generated by Django 3.0.2 on 2020-03-03 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc_pnn', '0002_auto_20200303_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pnndata',
            name='user',
        ),
    ]
