# Generated by Django 3.0.4 on 2020-03-21 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PnnData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('pnn_time', models.FloatField(verbose_name='pnn_time')),
                ('pnn_dev_time', models.FloatField(verbose_name='pnn_time')),
                ('pnn_data', models.FloatField(verbose_name='pnn')),
                ('pnn_dev_data', models.FloatField(verbose_name='pnn')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Measurement')),
            ],
        ),
        migrations.CreateModel(
            name='BeatData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('beat_data', models.CharField(max_length=6105, verbose_name='beat_data')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Measurement')),
            ],
        ),
    ]
