# Generated by Django 3.0.4 on 2020-03-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_pnn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beatdata',
            name='time',
            field=models.TimeField(verbose_name='beat_time'),
        ),
        migrations.AlterField(
            model_name='pnndata',
            name='time',
            field=models.TimeField(verbose_name='time'),
        ),
    ]
