# Generated by Django 3.0.4 on 2020-03-14 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calc_pnn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnndata',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
