# Generated by Django 3.0.4 on 2020-03-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_pnn', '0002_pnndata_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnndata',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
