# Generated by Django 3.0.4 on 2020-03-21 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc_pnn', '0002_auto_20200321_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pnndata',
            name='pnn_dev_data',
        ),
        migrations.RemoveField(
            model_name='pnndata',
            name='pnn_dev_time',
        ),
    ]
