# Generated by Django 3.0.4 on 2020-03-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_pnn', '0003_auto_20200321_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beatdata',
            name='beat_data',
            field=models.TextField(verbose_name='beat_data'),
        ),
    ]
