# Generated by Django 3.0.4 on 2020-03-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_pnn', '0004_auto_20200321_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beatdata',
            name='beat_data',
            field=models.CharField(max_length=6105, verbose_name='beat_data'),
        ),
    ]
