# Generated by Django 3.0.2 on 2020-02-01 06:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analysisAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartBeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='計測日時')),
                ('heart_beat_data', models.IntegerField(blank=True, default=0, verbose_name='心拍数データ')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, default=None, verbose_name='ユーザーid')),
                ('user_name', models.CharField(max_length=255, verbose_name='ユーザー名')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='')),
            ],
        ),
        migrations.DeleteModel(
            name='HeartBeatData',
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysisAPI.User'),
        ),
    ]
