# Generated by Django 2.2.10 on 2020-03-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200325_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='which_sex',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='sex'),
        ),
    ]
