# Generated by Django 3.0.2 on 2020-01-26 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeartBeatData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ユーザー名')),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='計測日時')),
                ('heart_beat_data', models.IntegerField(blank=True, default=0, verbose_name='心拍数データ')),
            ],
        ),
    ]
